### ISSUE TITLE
Class Not Found Error w/ NC 2o2.7

### ISSUE THREAD

**Issue by nephatrine** [Lach01298/QMD#11]
Just updated to NuclearCraft Overhaul 2o2.7 and server refuses to start now. Looks like one of the NC classes must have changed?

```
java.lang.NoClassDefFoundError: nc/util/ItemStackHelper
    at lach_01298.qmd.recipes.QMDCraftingRecipeHandler.registerRecipe(QMDCraftingRecipeHandler.java:229)
    at lach_01298.qmd.recipes.QMDCraftingRecipeHandler.addShapedOreRecipe(QMDCraftingRecipeHandler.java:197)
    at lach_01298.qmd.recipes.QMDCraftingRecipeHandler.registerCraftingRecipes(QMDCraftingRecipeHandler.java:56)
    at lach_01298.qmd.recipes.QMDRecipes.addRecipes(QMDRecipes.java:212)
    at lach_01298.qmd.recipes.QMDRecipes.registerRecipes(QMDRecipes.java:80)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2165_QMDRecipes_registerRecipes_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: nc.util.ItemStackHelper
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 17 more
Caused by: java.lang.NullPointerException
```

**Comment by pablocnvs** [comment]
It is a known issue, and there is already a stable build with compatibility in the Nuclearcraft Discord. I think it is 0.6.3. You can use that until Lach releases an update.

**Comment by Lach01298** [comment]
Will be solved. It becuse Nuclearcraft keeps changing/renaming methods.
