### ISSUE TITLE
Doesn't work with NuclearCraft Overhaul v2o.3.0 

### ISSUE THREAD

**Issue by marcin212** [Lach01298/QMD#19]
Crash after update NC from 2o.2.7 to v2o.3.0 :
```

java.lang.NoSuchFieldError: alloy_furnace
	at lach_01298.qmd.recipes.QMDRecipes.addRecipes(QMDRecipes.java:114)
	at lach_01298.qmd.recipes.QMDRecipes.registerRecipes(QMDRecipes.java:83)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1893_QMDRecipes_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by BrisingrAerowing** [comment]
It appears the type of that field was changed.

[Relevant Diff](https://github.com/turbodiesel4598/NuclearCraft/commit/4d01133a1473aaa1c5e114ed2f3534920fba5be3#diff-bbd11be5e2a24787460fb51334eb740b)
