### ISSUE TITLE
ComputerPort cause server Crash onMachineAssembled

### ISSUE THREAD

**Issue by jamys94** [Lach01298/QMD#38]
Not the first time it causes the crash. I attach the following crash log:

`java.lang.IllegalArgumentException: Cannot set property PropertyBool{name=frame, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=qmd:accelerator_computer_port, properties=[active, facing]}
    at pl.asie.foamfix.common.FoamyBlockState.withProperty(FoamyBlockState.java:57)
    at lach_01298.qmd.accelerator.tile.TileAcceleratorComputerPort.onMachineAssembled(TileAcceleratorComputerPort.java:46)
    at lach_01298.qmd.accelerator.tile.TileAcceleratorC
[crash-2020-12-21_16.08.26-server.txt](https://github.com/Lach01298/QMD/files/5725666/crash-2020-12-21_16.08.26-server.txt)
omputerPort.onMachineAssembled(TileAcceleratorComputerPort.java:24)
    at nc.multiblock.Multiblock.assembleMachine(Multiblock.java:369)
    at nc.multiblock.Multiblock.checkIfMachineIsWhole(Multiblock.java:357)
    at nc.multiblock.MultiblockWorldRegistry.processMultiblockChanges(MultiblockWorldRegistry.java:213)
    at nc.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:92)
    at nc.multiblock.MultiblockHandler.onWorldTick(MultiblockHandler.java:43)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1556_MultiblockHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)`

**Comment by Lach01298** [comment]
simple fix. will be fixed in next version. For now don't put the computer ports on the edges
