### ISSUE TITLE
QMD MultiBlock Tile Crash

### ISSUE THREAD

**Issue by cheesebobi** [Lach01298/QMD#77]
Hello! I updated my server today (Kuba's Modded Factions) and everything was running smoothly but suddenly we crashed with this log. If I am reading correctly it seems to be something to do with QMD. Hopefully, this will help, feel free to ask for anything and I shall do my best to be useful. My discord: cheesebobi#8233

_Time: 2022-05-18 15:22:17 BST
Description: Exception in server tick loop

java.lang.NoSuchMethodError: nc.multiblock.tile.TileMultiblockPart.(Ljava/lang/Class;)V
    at lach_01298.qmd.multiblock.TileCuboidalOrToroidalMultiblockPart.(TileCuboidalOrToroidalMultiblockPart.java:42)
    at lach_01298.qmd.accelerator.tile.TileAcceleratorPart.(TileAcceleratorPart.java:14)
    at lach_01298.qmd.accelerator.tile.TileAcceleratorGlass.(TileAcceleratorGlass.java:15)
    at lach_01298.qmd.accelerator.block.BlockAcceleratorGlass.createNewTileEntity(BlockAcceleratorGlass.java:27)
    at net.minecraft.block.Block.createTileEntity(Block.java:1300)
    at net.minecraft.world.chunk.Chunk.createNewTileEntity(Chunk.java:856)
    at net.minecraft.world.chunk.Chunk.getTileEntity(Chunk.java:877)
    at net.minecraft.world.World.getTileEntity(World.java:2747)
    at net.minecraft.world.WorldServer.getTileEntity(WorldServer.java:237)
    at mekanism.common.util.MekanismUtils.getTileEntity(MekanismUtils.java:1085)
    at mekanism.common.tile.transmitter.TileEntitySidedPipe.canConnectMutual(TileEntitySidedPipe.java:261)
    at mekanism.common.tile.transmitter.TileEntitySidedPipe.getPossibleTransmitterConnections(TileEntitySidedPipe.java:132)
    at mekanism.common.tile.transmitter.TileEntitySidedPipe.onLoad(TileEntitySidedPipe.java:487)
    at net.minecraft.world.World.addTileEntity(World.java:2260)
    at net.minecraft.world.World.addTileEntities(World.java:2287)
    at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:942)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:93)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:133)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:104)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:98)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:152)
    at net.minecraft.world.World.getChunk(World.java:445)
    at net.minecraft.world.World.getChunk(World.java:440)
    at net.minecraft.world.World.getTileEntity(World.java:2747)
    at net.minecraft.world.WorldServer.getTileEntity(WorldServer.java:237)
    at codechicken.chunkloader.manager.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:360)
    at codechicken.chunkloader.manager.ChunkLoaderManager$PlayerOrganiser.revive(ChunkLoaderManager.java:390)
    at codechicken.chunkloader.manager.OrganiserStorage$SavedData.onDimensionRevive(OrganiserStorage.java:217)
    at codechicken.chunkloader.manager.ChunkLoaderManager.processLoaderStates(ChunkLoaderManager.java:704)
    at codechicken.chunkloader.manager.ChunkLoaderManager.onTickEnd(ChunkLoaderManager.java:670)
    at codechicken.chunkloader.handler.ChunkLoaderEventHandler.worldTick(ChunkLoaderEventHandler.java:32)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1237_ChunkLoaderEventHandler_worldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:278)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:998)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:865)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
    at java.lang.Thread.run(Thread.java:748)_

**Comment by Lach01298** [comment]
Can you post the full crash log? Chances are your using the wrong NCO version because QMD hasn't been updated to the latest version yet.

**Comment by cheesebobi** [comment]
You are in fact correct, sorry for wasting your time, I was looking at the wrong crash report. 

Great mod btw, keep up the good work! And if you ever wanna come on the server and check out how the player base is using your mod feel free to hit me up.
