### ISSUE TITLE
`crafttweaker.log` error `qmd_target_chamber recipe was the wrong size`

### ISSUE THREAD

**Issue by Krutoy242** [Lach01298/QMD#90]
After updating to QMD-1.3-beta, i got this error:

```less
[ERROR] A qmd_target_chamber recipe was the wrong size
[ERROR] At least one QMD CraftTweaker recipe removal method has errored - check the CraftTweaker log for more details
[ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: mods\qmd.zs}: null
java.lang.NullPointerException
	at lach_01298.qmd.recipe.QMDRecipeHelper.getItemIngredientNames(QMDRecipeHelper.java:642)
	at lach_01298.qmd.recipe.QMDRecipeHelper.getAllIngredientNamesConcat(QMDRecipeHelper.java:687)
	at lach_01298.qmd.crafttweaker.RemoveQMDRecipe.describe(RemoveQMDRecipe.java:109)
	at youyihj.zenutils.impl.delegate.ZenUtilsTweaker.validateAction(ZenUtilsTweaker.java:177)
	at youyihj.zenutils.impl.delegate.ZenUtilsTweaker.apply(ZenUtilsTweaker.java:35)
	at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:151)
	at lach_01298.qmd.crafttweaker.QMDCraftTweaker$TargetChamberHandler.removeRecipeWithInput(QMDCraftTweaker.java:161)
	at mods\Qmd.__script__(mods\qmd.zs:171)
	at __ZenMain__.run(mods\Qmd)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:240)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
	at youyihj.zenutils.impl.delegate.ZenUtilsTweaker.loadScript(ZenUtilsTweaker.java:82)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:71)
```

Line `scripts/mods/qmd.zs:171` content:
```typescript
mods.qmd.target_chamber.removeRecipeWithInput(<qmd:semiconductor:3>, ((<particle:boron_ion>*1000000)^600)~2.0);
```
https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/fcbacf9770208f0b1dec5b38adba6ae53f3f8188/scripts/mods/qmd.zs#L175C1-L175C1

**Comment by Lach01298** [comment]
Fixed in 1.3 beta2
